export const env = {
  NODE_ENV: 'test' as const,
  LOG_LEVEL: 'silent' as const,
  PORT: 3000,
  JWT_SECRET: 'test-secret-key-minimum-32-characters-long!!',
  MONGODB_URI: 'mongodb://localhost:27017/test',
  REDIS_URL: 'redis://localhost:6379',
  GOOGLE_CLIENT_ID: 'test-google-client-id',
  GOOGLE_CLIENT_SECRET: 'test-google-client-secret',
  GOOGLE_REDIRECT_URI: 'http://localhost:3000/api/v1/auth/google/callback',
  MICROSOFT_CLIENT_ID: 'test-microsoft-client-id',
  MICROSOFT_CLIENT_SECRET: 'test-microsoft-client-secret',
  MICROSOFT_TENANT_ID: 'common',
  MICROSOFT_REDIRECT_URI: 'http://localhost:3000/api/v1/auth/microsoft/callback',
  ALLOWED_ORIGINS: 'http://localhost:5173',
  FRONTEND_URL: 'http://localhost:5173',
  RATE_LIMIT_WINDOW_MS: 900000,
  RATE_LIMIT_MAX_AUTH: 20,
  RATE_LIMIT_MAX_API: 200,
};